### ISSUE TITLE
Roles assigned people not displayed correctly

### ISSUE THREAD

**Issue by leader80** [digitalfondue/lavagna#1]
Hi Lavagna crew,

while entering the role tab in the setting section of my dashboard I just see the list of Roles but I don't see who is assigned to them. 
Only after typing the name of somebody belonging to the Lavagna project I see who belongs to which group, is this behavior correct?

**Comment by syjer** [comment]
Hi, yep, you are right :).

Will be fixed in the next milestone.

**Comment by syjer** [comment]
as a note: to reproduce this problem: the user must not be a an administrator but it must have the project admin role.

**Comment by syjer** [comment]
should be fixed. I've deployed on openshift the latest commit.

**Comment by leader80** [comment]
while landing on the roles page (under the dash settings) I still don't see the assigned people.

**Comment by syjer** [comment]
whelp, I'll check

**Comment by syjer** [comment]
should *really* be fixed and deployed on openshift, thanks for the report :D

**Comment by leader80** [comment]
Seems okay right now to me, good job!
