### ISSUE TITLE
Backlog count in project summary on dashboard

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#54]
I created some cards and move them into the backlog for my project.
![project backlog](https://cloud.githubusercontent.com/assets/8817923/22130391/fd34b104-deab-11e6-87fe-e89fe04cfeef.png)

But on the dashboard, I can not see a correct count for the backlog.
![sum project](https://cloud.githubusercontent.com/assets/8817923/22130420/223f5526-deac-11e6-94d1-e14b0e7b4307.png)

**Comment by syjer** [comment]
Hi @ejouvin , yes, this effectively not intuitive: the count is only for the active columns in the board with the backlog  status and not for the cards in the "Backlog sidebar"

But I think you are right, for the Backlog, we should do the sum. Thanks for the report, we will fix it :)

**Comment by syjer** [comment]
should be fixed now :)

**Comment by ejouvin** [comment]
Hum, really fixed ?
Just installed the current master branch, but still the same on the dashboard.

The dashboard :
![dashboard](https://cloud.githubusercontent.com/assets/8817923/22167099/9765e0b4-df64-11e6-8a23-7126d51d3ca9.png)

One project content :
![project backlog](https://cloud.githubusercontent.com/assets/8817923/22167119/b09d144e-df64-11e6-8295-a5cb506903dd.png)

The backlog count is still 0.
But may be, this is not fixed but not registered as a possible enhancement ?

**Comment by syjer** [comment]
Uh, I'll do a recheck

**Comment by ejouvin** [comment]
The value is correct in the Milestones section.

**Comment by syjer** [comment]
I've re-tested and it seems to work correctly with the dev environment (+hsqldb).

Maybe it's some kind of caching ?

if you go to : 

http://<your lavagna installation>/api/project/SERVEU/task-statistics what you see?

**Comment by syjer** [comment]
Ok, maybe I see, there is an inconsistency on our side. I'll do a new fix :D. Thanks for checking

**Comment by syjer** [comment]
If it's not a caching issue: what database are you using?

**Comment by ejouvin** [comment]
Huum...

I am using MySQL, and just upgrade from the master branch tonight.
And I think, I made a mistake when "reopening" the case.... I think I did not really update my instance.

Anyway, it is working as expected now.

**Comment by syjer** [comment]
thank you for the confirmation :)
